apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  JWT_SEED: c3VwZXJjaGljYUBnbWFpbC5jb20=  # base64 encoded value of 'superchica@gmail.com'