apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  DB_PASSWORD: cG9zdGdyZXM=  # base64 encoded value of 'postgres'